Repository codex-semantics-library/patricia-tree, pull requests merged in 2024-05, with the labels that each got.

#4 Remove dissappeared
  CHANGELOG.md
  patriciaTree.ml
Labels: bug

#6 New functions: fold_on_nonequal_inter and fold_on_nonequal_union
  patriciaTree.ml
  patriciaTree.mli
  patriciaTreeTest.ml
Labels: enhancement

#1 Hashconsed maps nodes
  CHANGELOG.md
  README.md
  dune-project
  index.mld
  patricia-tree.opam
  patriciaTree.ml
  patriciaTree.mli
  patriciaTreeTest.ml
Labels: enhancement

#5 Mdx
  .github/workflows/ocaml.yml
  CHANGELOG.md
  README.md
  dune
  dune-project
  index.mld
  patricia-tree.opam
  patriciaTree.ml
  patriciaTree.mli
Labels: documentation
